DROP TABLE IF EXISTS banners;
DROP SEQUENCE IF EXISTS banners_id_seq;
CREATE TABLE IF NOT EXISTS banners
(
    id     INTEGER PRIMARY KEY ,
    name   VARCHAR(200) NOT NULL ,
    path   VARCHAR(400) NOT NULL ,
    type   VARCHAR(20) NOT NULL ,
    status BOOLEAN ,
    drm    VARCHAR(10) NOT NULL
);
CREATE SEQUENCE banners_id_seq START WITH 25 INCREMENT BY 1;